### ISSUE TITLE
Using goccy/go-json instead of encoding/json fails a few tests in an existing project

### ISSUE THREAD

**Issue by vearutop** [goccy/go-json#119]
This draft PR https://github.com/swaggest/rest/pull/24 migrates to `goccy/go-json` by changing imports. Unfortunately such a change leads to test failures and a panic. 

Relevant GitHub Actions log: https://github.com/swaggest/rest/pull/24/checks?check_run_id=1861642353.

<details>
<summary>Panic message.</summary>

```
panic: runtime error: index out of range [824626223968] with length 730624 [recovered]
	panic: runtime error: index out of range [824626223968] with length 730624

goroutine 28 [running]:
testing.tRunner.func1.1(0xe85180, 0xc0006c8a80)
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1072 +0x46a
testing.tRunner.func1(0xc001370000)
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1075 +0x636
panic(0xe85180, 0xc0006c8a80)
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:975 +0x47a
github.com/goccy/go-json.(*Decoder).compileToGetDecoder(0xc001265278, 0xc0006e2d00, 0xc0006e2d00, 0x0, 0x0, 0x440191, 0x417ed0)
	/home/runner/work/rest/rest/vendor/github.com/goccy/go-json/decode_compile_race.go:16 +0x412
github.com/goccy/go-json.(*Decoder).decode(0xc001265278, 0xc0006c8a60, 0x14, 0x14, 0xc0000e7238, 0x4837e0, 0x4837e0)
	/home/runner/work/rest/rest/vendor/github.com/goccy/go-json/decode.go:71 +0x125
github.com/goccy/go-json.(*Decoder).decodeForUnmarshal(0xc001265278, 0xc0006c8a60, 0x14, 0x14, 0xc0006e2d00, 0xc00136a360, 0xc0006e2d00, 0xc00136a360)
	/home/runner/work/rest/rest/vendor/github.com/goccy/go-json/decode.go:84 +0x9b
github.com/goccy/go-json.Unmarshal(0xc0012652f8, 0x13, 0x20, 0xc0006e2d00, 0xc00136a360, 0x20, 0x4345f8)
	/home/runner/work/rest/rest/vendor/github.com/goccy/go-json/json.go:268 +0xe5
github.com/swaggest/rest/request.(*DecoderFactory).jsonParams.func1.1(0xc0006c8a40, 0x13, 0xc0012658b8, 0xc00134f8e8, 0xe4fe01, 0x101)
	/home/runner/work/rest/rest/request/factory.go:164 +0x3bb
github.com/swaggest/form.(*decoder).setFieldByType(0xc0006da900, 0xe4fee0, 0xc00136a300, 0x199, 0xc0006bee40, 0x6, 0x40, 0x0, 0x5)
	/home/runner/work/rest/rest/vendor/github.com/swaggest/form/decoder.go:194 +0x79c2
github.com/swaggest/form.(*decoder).traverseStruct(0xc0006da900, 0xe48660, 0xc00136a300, 0x199, 0x1143c20, 0xe48660, 0xc0006bee40, 0x0, 0x40, 0x0)
	/home/runner/work/rest/rest/vendor/github.com/swaggest/form/decoder.go:175 +0x385
github.com/swaggest/form.(*Decoder).Decode(0xc0006e2c80, 0xe0e920, 0xc00136a300, 0xc00130ff50, 0x0, 0x0, 0x0, 0x418620, 0xc0006b1cc0)
	/home/runner/work/rest/rest/vendor/github.com/swaggest/form/form_decoder.go:166 +0x385
github.com/swaggest/rest/request.makeDecoder.func1(0xc0006b9d00, 0xe0e920, 0xc00136a300, 0x0, 0x0, 0x5a191e, 0xc001370000)
	/home/runner/work/rest/rest/request/decoder.go:40 +0x213
github.com/swaggest/rest/request.(*decoder).Decode(0xc00130fe60, 0xc0006b9d00, 0xe0e920, 0xc00136a300, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/rest/rest/request/decoder.go:55 +0x14b
github.com/swaggest/rest/request_test.TestDecoder_Decode_jsonParam(0xc001370000)
	/home/runner/work/rest/rest/request/decoder_test.go:305 +0x179
testing.tRunner(0xc001370000, 0xef5d48)
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1168 +0x5bc
```

</details>

**Comment by goccy** [comment]
Thank you for reporting ! I fixed this issue with #120 and released as `v0.4.2` .
Please try it 🙇
