### ISSUE TITLE
json.Compact has an incompatible behavior

### ISSUE THREAD

**Issue by orisano** [goccy/go-json#125]
I have encountered an incompatible behavior.
https://gist.github.com/orisano/8aa749cd50fece0a61694ee60b87a208

## Source
```go
package main

import (
	"bytes"
	"testing"
	
	stdjson "encoding/json"
	gojson "github.com/goccy/go-json"
)

func TestCompact(t *testing.T) {
	src := []byte(`"\`)
	if err := stdjson.Compact(bytes.NewBuffer(nil), src); err != nil {
		t.Error(err)
	}
	if err := gojson.Compact(bytes.NewBuffer(nil), src); err != nil {
		t.Error(err)
	}
}
```

## Result
```
--- FAIL: TestCompact (0.00s)
    compact_test.go:14: invalid character ' ' in string escape code
panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: runtime error: index out of range [2] with length 2

goroutine 49 [running]:
testing.tRunner.func1.1(0x1144440, 0xc0006a8020)
	/Users/orisano/sdk/go1.15.6/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000682480)
	/Users/orisano/sdk/go1.15.6/src/testing/testing.go:1075 +0x41a
panic(0x1144440, 0xc0006a8020)
	/Users/orisano/sdk/go1.15.6/src/runtime/panic.go:969 +0x1b9
github.com/goccy/go-json.compact(0xc000066f20, 0xc000066f0e, 0x2, 0x2, 0x106b300, 0x1197e80, 0xc00069c020)
	/Users/orisano/go/pkg/mod/github.com/goccy/go-json@v0.4.3/compact.go:34 +0x469
github.com/goccy/go-json.Compact(...)
	/Users/orisano/go/pkg/mod/github.com/goccy/go-json@v0.4.3/json.go:349
gojson.TestCompact(0xc000682480)
	/Users/orisano/works/gojson/compact_test.go:16 +0x125
testing.tRunner(0xc000682480, 0x11758b8)
	/Users/orisano/sdk/go1.15.6/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/Users/orisano/sdk/go1.15.6/src/testing/testing.go:1168 +0x2b3
exit status 2
FAIL	gojson	0.290s
```

go-json panicked.
Maybe cause is here.
https://github.com/goccy/go-json/blob/7ffe1ddb3521e9abb485d5c47cf265fb74bea347/compact.go#L32-L36

What is the correct behavior?

**Comment by aaron42net** [comment]
A similar bug in the same function can be triggered by marshaling a raw.Message:

```
package main

import (
        "fmt"

        json "github.com/goccy/go-json"
//      "encoding/json"
)

type Foo struct {
        A json.RawMessage
}

func main() {
        input := []byte(`{"a":"\\""}`)
        foo := &Foo{}
        err := json.Unmarshal(input, foo)
        fmt.Println(foo, err)

        output, err := json.Marshal(foo)
        fmt.Println(output, err)
}
```

Which produces:
```
$ go run -trimpath main.go
&{A:[34 92 92 34 34]} <nil>
panic: runtime error: index out of range [5] with length 5

goroutine 1 [running]:
github.com/goccy/go-json/internal/encoder.Compact(0xc00007ce78, 0xc0000160b0, 0x5, 0x8, 0x1, 0x0, 0x0)
	github.com/goccy/go-json@v0.4.11/internal/encoder/compact.go:25 +0x55f
github.com/goccy/go-json/internal/encoder.AppendMarshalJSON(0xc000496500, 0xc000492000, 0x5, 0x400, 0x11a67a0, 0xc00000c060, 0x1, 0x0, 0x0, 0x0, ...)
	github.com/goccy/go-json@v0.4.11/internal/encoder/encoder.go:438 +0x3ca
github.com/goccy/go-json/internal/encoder/vm_escaped.Run(0xc000494000, 0xc000492000, 0x1, 0x400, 0xc00000c0d8, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/goccy/go-json@v0.4.11/internal/encoder/vm_escaped/vm.go:2721 +0x11145
github.com/goccy/go-json.encodeRunCode(0xc000494000, 0xc000492000, 0x0, 0x400, 0xc00000c0d8, 0x1, 0xc000492400, 0xc000492000, 0xc00007ddd0, 0x107852a, ...)
	github.com/goccy/go-json@v0.4.11/encode.go:281 +0x7e
github.com/goccy/go-json.encode(0xc000494000, 0x119da00, 0xc00000c060, 0x1, 0x10783fc, 0x12be100, 0xc000490000, 0x0, 0xc00007de48)
	github.com/goccy/go-json@v0.4.11/encode.go:211 +0x215
github.com/goccy/go-json.marshal(0x119da00, 0xc00000c060, 0x1, 0x0, 0x0, 0x1c, 0xc000060dd0, 0x0)
	github.com/goccy/go-json@v0.4.11/encode.go:135 +0x85
github.com/goccy/go-json.MarshalWithOption(0x119da00, 0xc00000c060, 0x0, 0x0, 0x0, 0x2, 0x2, 0x1c, 0x0, 0x0)
	github.com/goccy/go-json@v0.4.11/json.go:172 +0x76
github.com/goccy/go-json.Marshal(...)
	github.com/goccy/go-json@v0.4.11/json.go:158
main.main()
	command-line-arguments/main.go:20 +0x167
exit status 2
```
