### ISSUE TITLE
[FOLLOW UP] - https://github.com/goccy/go-json/issues/104

### ISSUE THREAD

**Issue by sujit-baniya** [goccy/go-json#149]
https://github.com/goccy/go-json/issues/104

I'm still getting same issue on same place

```go
encoder (escaped): opcode StructFieldOmitEmptyStruct has not been implemented
```

**Comment by goccy** [comment]
Could you tell me installed go-json's version ?

**Comment by sujit-baniya** [comment]
@goccy github.com/goccy/go-json v0.4.7

**Comment by goccy** [comment]
@sujit-baniya Since I don't release a new version, I expect to you use master branch's HEAD ( by `go get github.com/goccy/go-json@master` )

**Comment by sujit-baniya** [comment]
@goccy Ok Let me try. When are you planning for release?

**Comment by goccy** [comment]
@sujit-baniya I plan to further improve the memory usage at compile time and the stability of the encoder, and release it within a week.

**Comment by sujit-baniya** [comment]
@goccy  That seems to make it work.

**Comment by sujit-baniya** [comment]
@goccy Now I'm facing more serious issue

```go
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x41950a]

goroutine 377 [running]:
runtime.throw(0x159dfd8, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000895be0 sp=0xc000895bb0 pc=0x43f7b2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc000895c18 sp=0xc000895be0 pc=0x4561a8
runtime.evacuated(...)
        /usr/local/go/src/runtime/map.go:203
runtime.mapiternext(0xc001d14540)
        /usr/local/go/src/runtime/map.go:881 +0x48a fp=0xc000895c98 sp=0xc000895c18 pc=0x41950a
runtime.mapiterinit(0x14078e0, 0xc0012e7268, 0xc001d14540)
        /usr/local/go/src/runtime/map.go:848 +0x1c5 fp=0xc000895cb8 sp=0xc000895c98 pc=0x418f85
reflect.mapiterinit(0x14078e0, 0xc0012e7268, 0xc00)
        /usr/local/go/src/runtime/map.go:1340 +0x54 fp=0xc000895ce8 sp=0xc000895cb8 pc=0x46fdb4
github.com/goccy/go-json.encodeRunEscaped(0xc000476000, 0xc000388000, 0x2f0, 0xc00, 0xc00065da20, 0x1, 0xc00ba6e1db7e3487, 0x1295c43717, 0x23ca3c0, 0x0, ...)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/encode_vm_escaped.go:295 +0x2a91 fp=0xc000896b58 sp=0xc000895ce8 pc=0x81f251
github.com/goccy/go-json.encodeRunCode(0xc000476000, 0xc000388000, 0x0, 0xc00, 0xc00065da20, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/encode.go:280 +0x74 fp=0xc000896bc0 sp=0xc000896b58 pc=0x7daa54
github.com/goccy/go-json.encode(0xc000476000, 0x13996e0, 0xc0001688a0, 0x1, 0xc000642420, 0x0, 0x1295c43717, 0xc00ba6e1db7e3487, 0x3)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/encode.go:209 +0x1df fp=0xc000896c88 sp=0xc000896bc0 pc=0x7da71f
github.com/goccy/go-json.marshal(0x13996e0, 0xc0001688a0, 0x1, 0x0, 0x0, 0xc000be0cc0, 0x9, 0xc000642420)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/encode.go:135 +0x85 fp=0xc000896d10 sp=0xc000896c88 pc=0x7da3c5
github.com/goccy/go-json.MarshalWithOption(0x13996e0, 0xc0001688a0, 0x0, 0x0, 0x0, 0x18, 0x13d5320, 0xc00003eea0, 0x1e, 0x7fd98a94a848)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/json.go:171 +0x76 fp=0xc000896d68 sp=0xc000896d10 pc=0x84dd16
github.com/goccy/go-json.Marshal(0x13996e0, 0xc0001688a0, 0xc0001688a0, 0x0, 0xc000035c00, 0x0, 0xc000896e28)
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210311171440-3ee1ab271152/json.go:157 +0x46 fp=0xc000896dc8 sp=0xc000896d68 pc=0x84dc46
github.com/gofiber/fiber/v2.(*Ctx).JSON(0xc000828580, 0x13996e0, 0xc0001688a0, 0xc0001688a0, 0xc00014a000)
```

**Comment by goccy** [comment]
@sujit-baniya Thank you for your report.
If possible, could you please tell me the type information of the argument you passed when calling `json.Marshal` with` github.com/gofiber/fiber/v2.(*Ctx).JSON` ?
I think it contains the `map` type.

**Comment by sujit-baniya** [comment]
@goccy Yes it's map type

**Comment by goccy** [comment]
@sujit-baniya 
I know it contains a map type, but I want to know the specific type e.g.) `map[string]interface{}` .
Because many tests using map type has passed ( these tests ( https://github.com/goccy/go-json/blob/master/encode_test.go#L319-L328 or https://github.com/goccy/go-json/blob/master/cover_map_test.go ) ) .

**Comment by sujit-baniya** [comment]
Ah @goccy it's 

```go
map[string]map[string]int
```

**Comment by goccy** [comment]
@sujit-baniya Thank you for the type information . I fixed the issue with https://github.com/goccy/go-json/pull/150

**Comment by sujit-baniya** [comment]
@goccy I'll try it out... One thing I noticed, in your test cases, you have used `map[string]int` 

The map can be different. For e.g.

`map[string]string` map[string]struct` `map[string]map[...]`

**Comment by sujit-baniya** [comment]
@goccy Still there are other issues with latest master. 

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7bc8fa]

goroutine 1 [running]:
github.com/goccy/go-json/internal/encoder.init.0()
        /home/sujit/go/pkg/mod/github.com/goccy/go-json@v0.4.8-0.20210319151453-094f8da49e66/internal/encoder/compiler.go:27 +0x3a

```

**Comment by goccy** [comment]
@sujit-baniya Thank you, I fixed it with https://github.com/goccy/go-json/pull/156 .

**Comment by goccy** [comment]
I released [v0.4.8](https://github.com/goccy/go-json/releases/tag/v0.4.8) !
Please checked it out !

**Comment by dynamix** [comment]
I have been running into the same `encoder (escaped): opcode StructFieldPtrHeadOmitEmptySlice has not been implemented`. After updating to v0.4.8 (I tried the current head as well) I'm seeing random crashes or a hanging process that just keeps allocating memory while running our project's test suite. 

It hangs in  `encoder.AppendEscapedString`

```
github.com/goccy/go-json/internal/encoder.AppendEscapedString(0xc1ba60e000, 0xb38fa47a, 0x8fa56000, 0xc00040b300, 0xc00079f170, 0x52e2880, 0x531edcf, 0xc0005dedd0)
	X/github.com/goccy/go-json/internal/encoder/string.go:531 +0x193
github.com/goccy/go-json/internal/encoder/vm_escaped.Run(0xc0001743c0, 0xc000a1e800, 0x11, 0x400, 0xc0018ebc50, 0x1, 0xc0009e7c10, 0x4011998, 0x98, 0x54e4a80, ...)
	X/github.com/goccy/go-json/internal/encoder/vm_escaped/vm.go:1580 +0xbf45
github.com/goccy/go-json.encodeRunCode(0xc0001743c0, 0xc000a1e800, 0x0, 0x400, 0xc0018ebc50, 0x1, 0xc000a1ec00, 0xc000a1e800, 0xc0009e7ca0, 0x408176a, ...)
	X/github.com/goccy/go-json/encode.go:276 +0x74
github.com/goccy/go-json.encode(0xc0001743c0, 0x55467c0, 0xc0004139c8, 0x1, 0x401123b, 0xc0004139c8, 0x8, 0x8, 0x5422240)
	X/github.com/goccy/go-json/encode.go:209 +0x215
github.com/goccy/go-json.marshal(0x55467c0, 0xc0004139c8, 0x1, 0xc0009e7d80, 0x4011998, 0x8, 0x5422240, 0x1)
	X/github.com/goccy/go-json/encode.go:133 +0x85
github.com/goccy/go-json.MarshalWithOption(0x55467c0, 0xc0004139c8, 0x0, 0x0, 0x0, 0x30, 0xc0009b8b10, 0x8, 0xc000080d80, 0x0)
	X/github.com/goccy/go-json/json.go:172 +0x76
github.com/goccy/go-json.Marshal(...)
	X/github.com/goccy/go-json/json.go:158
```

Adding some debug logging shows that the code is stuck in the for loop: https://github.com/goccy/go-json/blob/24b6dfedb4ec6c8d4eda78143b36422058a79cfe/internal/encoder/string.go#L444 because `valLen` is `824652350592`. 

This looks like memory corruption (if I use `encoding/json` all tests work.)

Unfortunalty I can't extract the test easily.

**Comment by goccy** [comment]
@dynamix 

Thank you for your report. However, I cannot debug with the information I received, so I created an option to output debug information. Can you paste the debug information output using `json.MarshalWithOption(v, json.Debug())` as shown that ? Also, in that case, I want to isolate the problem, so create it as a new issue.

https://github.com/goccy/go-json/pull/165

**Comment by dynamix** [comment]
@goccy understandable, I wanted to provide more information did not have the time to debug it in detail. The debug option sounds great - I'll do a run with it later today.

**Comment by dynamix** [comment]
Using the current master and running the test with the debug output yielded: 

```
=============[DEBUG]===============
* [TYPE]
*NativeResponseWrapper

* [ALL OPCODE]
[0]StructHeadOmitEmpty ([idx:0][key:native][offset:0][headIdx:0])
[1]-StructPtrHeadOmitEmptyString ([idx:1][key:ver][offset:0][headIdx:1])
[2]--StructFieldOmitEmptySlice ([idx:3][key:assets][offset:16][headIdx:1])
[3]--Slice ([idx:4][headIdx:4][elemIdx:5][length:6])
[4]---StructPtrHeadInt ([idx:7][key:id][offset:0][headIdx:7])
[5]----StructFieldOmitEmptyBool ([idx:9][key:required][offset:4][headIdx:7])
[6]----StructFieldOmitEmpty ([idx:10][key:title][offset:8][headIdx:7])
[7]----StructPtrHeadOmitEmptyString ([idx:11][key:text][offset:0][headIdx:11])
[8]----StructEnd ([idx:13][key:][offset:0][headIdx:0])
[9]----StructFieldOmitEmpty ([idx:14][key:img][offset:16][headIdx:7])
[10]----StructPtrHeadOmitEmptyString ([idx:15][key:url][offset:0][headIdx:15])
[11]-----StructFieldOmitEmptyInt ([idx:17][key:w][offset:16][headIdx:15])
[12]-----StructEndOmitEmptyInt ([idx:18][key:h][offset:20][headIdx:15])
[14]----StructFieldOmitEmpty ([idx:20][key:video][offset:24][headIdx:7])
[15]----StructPtrHeadOmitEmptyString ([idx:21][key:vasttag][offset:0][headIdx:21])
[16]----StructEnd ([idx:23][key:][offset:0][headIdx:0])
[17]----StructFieldOmitEmpty ([idx:24][key:data][offset:32][headIdx:7])
[18]----StructPtrHeadOmitEmptyString ([idx:25][key:label][offset:0][headIdx:25])
[19]-----StructEndOmitEmptyString ([idx:27][key:value][offset:16][headIdx:25])
[21]----StructFieldOmitEmpty ([idx:29][key:link][offset:40][headIdx:7])
[22]----StructPtrHeadOmitEmptyString ([idx:30][key:url][offset:0][headIdx:30])
[23]-----StructFieldOmitEmptySlice ([idx:32][key:clicktrackers][offset:16][headIdx:30])
[24]-----Slice ([idx:33][headIdx:33][elemIdx:34][length:35])
[25]------String ([idx:36])
[26]-----SliceElem ([idx:37][headIdx:33][elemIdx:34][length:35][size:16])
[27]-----SliceEnd ([idx:38])
[28]-----StructEndOmitEmptyString ([idx:39][key:fallback][offset:40][headIdx:30])
[30]---StructEnd ([idx:41][key:][offset:0][headIdx:0])
[31]--SliceElem ([idx:42][headIdx:4][elemIdx:5][length:6][size:8])
[32]--SliceEnd ([idx:43])
[33]--StructFieldOmitEmpty ([idx:44][key:link][offset:40][headIdx:1])
[34]--StructPtrHeadOmitEmptyString ([idx:45][key:url][offset:0][headIdx:45])
[35]---StructFieldOmitEmptySlice ([idx:47][key:clicktrackers][offset:16][headIdx:45])
[36]---Slice ([idx:48][headIdx:48][elemIdx:49][length:50])
[37]----String ([idx:51])
[38]---SliceElem ([idx:52][headIdx:48][elemIdx:49][length:50][size:16])
[39]---SliceEnd ([idx:53])
[40]---StructEndOmitEmptyString ([idx:54][key:fallback][offset:40][headIdx:45])
[42]--StructFieldSlice ([idx:56][key:imptrackers][offset:48][headIdx:1])
[43]--Slice ([idx:57][headIdx:57][elemIdx:58][length:59])
[44]---String ([idx:60])
[45]--SliceElem ([idx:61][headIdx:57][elemIdx:58][length:59][size:16])
[46]--SliceEnd ([idx:62])
[47]--StructFieldOmitEmptyString ([idx:63][key:jstracker][offset:72][headIdx:1])
[48]--StructFieldOmitEmptySlice ([idx:64][key:eventtrackers][offset:88][headIdx:1])
[49]--Slice ([idx:65][headIdx:65][elemIdx:66][length:67])
[50]---StructPtrHeadOmitEmptyInt ([idx:68][key:event][offset:0][headIdx:68])
[51]----StructFieldOmitEmptySlice ([idx:70][key:methods][offset:8][headIdx:68])
[52]----Slice ([idx:71][headIdx:71][elemIdx:72][length:73])
[53]-----Int ([idx:74])
[54]----SliceElem ([idx:75][headIdx:71][elemIdx:72][length:73][size:4])
[55]----SliceEnd ([idx:76])
[56]---StructEnd ([idx:77][key:][offset:0][headIdx:0])
[57]--SliceElem ([idx:78][headIdx:65][elemIdx:66][length:67][size:8])
[58]--SliceEnd ([idx:79])
[59]--StructEndOmitEmptyString ([idx:80][key:privacy][offset:112][headIdx:1])
[61]StructEnd ([idx:82][key:][offset:0][headIdx:0])

* [CURRENT OPCODE]
&{Op:StructPtrHeadOmitEmptyString Type:string DisplayIdx:1 Key:[34 118 101 114 34 58] EscapedKey:[34 118 101 114 34 58] PtrNum:1 DisplayKey:ver IsTaggedKey:true AnonymousKey:false AnonymousHead:false Indirect:false Nilcheck:true AddrForMarshaler:false IsNextOpPtrType:false IsNilableType:false RshiftNum:0 Mask:0 Indent:1 Idx:8 HeadIdx:8 ElemIdx:0 Length:0 MapIter:0 MapPos:0 Offset:0 Size:0 MapKey:<nil> MapValue:<nil> Elem:<nil> End:0xc00034db00 PrevField:<nil> NextField:0xc000382100 Next:0xc000382100 Jmp:<nil>}

* [CONTEXT]
&{Buf:[] Ptrs:[824648737368 824648737368 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] KeepRefs:[0xc000e52258] SeenPtr:[] BaseIndent:0 Prefix:[] IndentStr:[]}```

This time hanging in `encoder.AppendString` in the equivalent loop.

I added an additional debug output to log `varLen` which is `824659080064`. This looks like a pointer (`c00182f380`) to me and not the length of the string :-)

**Comment by goccy** [comment]
@dynamix 

>  I want to isolate the problem, so create it as a new issue.

Please create a new issue for the reported problem.
Since I fixed this with https://github.com/goccy/go-json/pull/168, I would like to refer to a new issue .

**Comment by goccy** [comment]
I think that the issue reported here has already been resolved, so I'll close it. If you have any problems, please create a new issue.
