### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by lcd1232** [goccy/go-json#298]
I decided to switch from "encoding/json" to this library but now I got an error in CI:
```
# github.com/goccy/go-json/internal/encoder/vm
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xc56088, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc028000000, 0x8000000, 0x11626b8)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x11455a0, 0x8000000, 0x42ba77, 0x11455a8)
	/usr/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x11455a0, 0x3f2c, 0x0)
	/usr/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x11455a0, 0x3f2c, 0x420100, 0x11626c8, 0x0)
	/usr/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x11455a0, 0x3f2c, 0x460001, 0x11455a0)
	/usr/local/go/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x7e58000, 0x100, 0x11455a0)
	/usr/local/go/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1116
goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc001c86bf8 sp=0xc001c86bf0 pc=0x46b360
runtime.mallocgc(0x7e58000, 0x0, 0x0, 0xc0028bab88)
	/usr/local/go/src/runtime/malloc.go:1070 +0x938 fp=0xc001c86c98 sp=0xc001c86bf8 pc=0x40dcb8
runtime.growslice(0xc13de0, 0xc01fbd0000, 0x651200, 0x651200, 0x651201, 0x10a1750, 0x1, 0x2)
	/usr/local/go/src/runtime/slice.go:224 +0x152 fp=0xc001c86d00 sp=0xc001c86c98 pc=0x44e312
cmd/compile/internal/ssa.(*debugState).appendLiveSlot(...)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:289
cmd/compile/internal/ssa.(*debugState).liveness(0xc0023cd660, 0xc001bbe401, 0xc00622d130, 0xc004b6f998)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:511 +0x7d6 fp=0xc001c86f00 sp=0xc001c86d00 pc=0x65f716
cmd/compile/internal/ssa.BuildFuncDebug(0xc0002f9380, 0xc000e20160, 0xc002cd9400, 0xc708a0, 0x6a9)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:435 +0xa88 fp=0xc001c871d0 sp=0xc001c86f00 pc=0x65e488
cmd/compile/internal/gc.genssa(0xc000e20160, 0xc000d6ca80)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:6164 +0x2885 fp=0xc001c876a0 sp=0xc001c871d0 pc=0xaf3f05
cmd/compile/internal/gc.compileSSA(0xc0000fde40, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:327 +0x3a5 fp=0xc001c87768 sp=0xc001c876a0 pc=0xa8a685
cmd/compile/internal/gc.compile(0xc0000fde40)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:275 +0x345 fp=0xc001c877e0 sp=0xc001c87768 pc=0xa8a125
cmd/compile/internal/gc.funccompile(0xc0000fde40)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:220 +0xc5 fp=0xc001c87838 sp=0xc001c877e0 pc=0xa89cc5
cmd/compile/internal/gc.Main(0xc70410)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:747 +0x344f fp=0xc001c87f10 sp=0xc001c87838 pc=0xa60f0f
main.main()
	/usr/local/go/src/cmd/compile/main.go:52 +0xb1 fp=0xc001c87f88 sp=0xc001c87f10 pc=0xba7df1
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc001c87fe0 sp=0xc001c87f88 pc=0x439409
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc001c87fe8 sp=0xc001c87fe0 pc=0x46cfa1
```

I'm not sure that problem with low CI machine because it builds successfully using "encoding/json"

**Comment by goccy** [comment]
This is duplicated issue . 
https://github.com/goccy/go-json/issues/289

Thanks
