### ISSUE TITLE
panic on encode

### ISSUE THREAD

**Issue by yukels** [goccy/go-json#451]
Hi
I'm trying to port my code to use the "go-json" instead of the standard json encoder. But I got a panic error on the object encoding.
the debug info and stack trace are below.

please advise

```
=============[DEBUG]===============
* [TYPE]
*dto.ClipDto

* [ALL OPCODE]
[000]-StructHead ([idx:0][key:ElasticClip][offset:0])
[001]-StructPtrHead ([idx:1][key:Clip][offset:0])
[002]-StructPtrHeadOmitEmptyMarshalJSONPtr ([idx:2][key:id][offset:0])
[003]-StructFieldOmitEmptyString ([idx:2][key:name][offset:8])
[004]-StructFieldOmitEmpty ([idx:2][key:continuousSession][offset:24])
[005]--StructPtrHeadOmitEmptyMarshalJSONPtr ([idx:5][key:id][offset:0])
[006]--StructFieldOmitEmptyStringPtr ([idx:5][key:name][offset:8])
[007]--StructFieldOmitEmptyStringPtr ([idx:5][key:project][offset:16])
[008]--StructFieldOmitEmptyStringPtr ([idx:5][key:dataOwner][offset:24])
[009]--StructFieldOmitEmptyMarshalJSONPtr ([idx:5][key:uploadDate][offset:32])
[010]--StructFieldOmitEmptyStringPtr ([idx:5][key:environmentType][offset:40])
[011]--StructFieldOmitEmptyBoolPtr ([idx:5][key:anonymized][offset:48])
[012]--StructFieldOmitEmpty ([idx:5][key:bypassLogging][offset:56])
[013]---StructPtrHeadOmitEmptyBoolPtr ([idx:13][key:availability][offset:0])
[014]---StructFieldOmitEmpty ([idx:13][key:validity][offset:8])
[015]----StructPtrHeadOmitEmptyString ([idx:15][key:isValid][offset:0])
[016]----StructEndOmitEmptyString ([idx:15][key:value][offset:16])
[017]---StructEnd ([idx:17][key:][offset:0])
[018]--StructFieldOmitEmptyStringPtr ([idx:5][key:onlineBrainVersion][offset:64])
[019]--StructFieldOmitEmptyIntPtr ([idx:5][key:mdbID][offset:72])
[020]--StructFieldOmitEmptyIntPtr ([idx:5][key:startFrameID][offset:80])
[021]--StructFieldOmitEmptyIntPtr ([idx:5][key:endFrameID][offset:88])
[022]--StructFieldOmitEmptyIntPtr ([idx:5][key:firstGfiIndex][offset:96])
[023]--StructFieldOmitEmptyIntPtr ([idx:5][key:lastGfiIndex][offset:104])
[024]--StructFieldOmitEmptyIntPtr ([idx:5][key:fps][offset:112])
[025]--StructFieldOmitEmptyUintPtr ([idx:5][key:tcVersion][offset:120])
[026]--StructFieldOmitEmptyIntPtr ([idx:5][key:numberOfCameras][offset:128])
[027]--StructFieldOmitEmptySlice ([idx:5][key:sensors][offset:136])
[028]--Slice ([idx:27][elemIdx:28][length:29])
[029]----StructPtrHeadOmitEmptyString ([idx:30][key:name][offset:0])
[030]----StructFieldOmitEmptyString ([idx:30][key:type][offset:16])
[031]----StructFieldOmitEmptyStringPtr ([idx:30][key:model][offset:32])
[032]----StructFieldOmitEmptySlice ([idx:30][key:validations][offset:40])
[033]----Slice ([idx:34][elemIdx:35][length:36])
[034]------StructPtrHead ([idx:37][key:Metadata][offset:0])
[035]------StructPtrHeadMarshalJSONPtr ([idx:38][key:id][offset:0])
[036]------StructFieldOmitEmptyStringPtr ([idx:38][key:category][offset:8])
[037]------StructFieldOmitEmptyMarshalJSONPtr ([idx:38][key:timestamp][offset:16])
[038]------StructFieldOmitEmpty ([idx:38][key:value][offset:24])
[039]------Interface ([idx:42])
[040]------StructFieldOmitEmptyBoolPtr ([idx:38][key:default][offset:40])
[041]------StructFieldOmitEmptyStringPtr ([idx:38][key:source][offset:48])
[042]------StructFieldOmitEmptyStringPtr ([idx:38][key:sourceDescription][offset:56])
[043]------StructFieldOmitEmptyStringPtr ([idx:38][key:isValid][offset:64])
[044]------StructFieldOmitEmptyStringPtr ([idx:38][key:referTo][offset:72])
[045]------StructEnd ([idx:48][key:][offset:0])
[046]----SliceElem ([idx:34][elemIdx:35][length:36][size:8])
[047]----SliceEnd ([idx:49])
[048]----StructFieldOmitEmptyStringPtr ([idx:30][key:propertyUniqueId][offset:64])
[049]----StructFieldOmitEmptyStringPtr ([idx:30][key:imageSensorType][offset:72])
[050]----StructFieldOmitEmptyStringPtr ([idx:30][key:lensType][offset:80])
[051]----StructFieldOmitEmptyBoolPtr ([idx:30][key:isDummy][offset:88])
[052]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:cameraHeight][offset:96])
[053]----StructFieldOmitEmpty ([idx:30][key:rollAngle][offset:104])
[054]----Interface ([idx:56])
[055]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:leftWheel][offset:120])
[056]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:rightWheel][offset:128])
[057]----StructFieldOmitEmptyStringPtr ([idx:30][key:loggingPort][offset:136])
[058]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:bottom][offset:144])
[059]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:top][offset:152])
[060]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:focalLength][offset:160])
[061]----StructFieldOmitEmptyIntPtr ([idx:30][key:cameraImageHeight][offset:168])
[062]----StructFieldOmitEmptyIntPtr ([idx:30][key:cameraImageWidth][offset:176])
[063]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:cameraImageResolution][offset:184])
[064]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:hfov][offset:192])
[065]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:pixelSize][offset:200])
[066]----StructFieldOmitEmptyFloat64Ptr ([idx:30][key:lensShift][offset:208])
[067]----StructFieldOmitEmptySlicePtr ([idx:30][key:distortParams][offset:216])
[068]----Slice ([idx:70][elemIdx:71][length:72])
[069]-----Float64 ([idx:73])
[070]----SliceElem ([idx:70][elemIdx:71][length:72][size:8])
[071]----SliceEnd ([idx:75])
[072]----StructFieldOmitEmptyIntPtr ([idx:30][key:sbsSensorId][offset:224])
[073]----StructFieldOmitEmptyMapPtr ([idx:30][key:pyramids][offset:232])
[074]----Map ([idx:78])
[075]----String ([idx:80])
[076]----MapValue ([idx:78])
[077]-----Slice ([idx:82][elemIdx:83][length:84])
[078]------String ([idx:85])
[079]-----SliceElem ([idx:82][elemIdx:83][length:84][size:16])
[080]-----SliceEnd ([idx:87])
[081]----MapKey ([idx:78])
[082]----MapEnd ([idx:78])
[083]----StructFieldOmitEmptyIntPtr ([idx:30][key:fps][offset:240])
[084]----StructFieldOmitEmptyStringPtr ([idx:30][key:physicalLocation][offset:248])
[085]----StructFieldOmitEmptyStringPtr ([idx:30][key:sn][offset:256])
[086]----StructFieldOmitEmptyStringPtr ([idx:30][key:fw][offset:264])
[087]----StructFieldOmitEmptyStringPtr ([idx:30][key:lidarParse][offset:272])
[088]----StructEndOmitEmptyStringPtr ([idx:30][key:inClip][offset:280])
[089]--SliceElem ([idx:27][elemIdx:28][length:29][size:8])
[090]--SliceEnd ([idx:97])
[091]--StructFieldOmitEmptySlice ([idx:5][key:connectedContinuousSessions][offset:160])
[092]--Slice ([idx:99][elemIdx:100][length:101])
[093]---MarshalJSON ([idx:102])
[094]--SliceElem ([idx:99][elemIdx:100][length:101][size:12])
[095]--SliceEnd ([idx:104])
[096]--StructFieldOmitEmpty ([idx:5][key:viewInfo][offset:184])
[097]---StructPtrHeadOmitEmptyStringPtr ([idx:106][key:viewName][offset:0])
[098]---StructFieldOmitEmptyStringPtr ([idx:106][key:viewType][offset:8])
[099]---StructFieldOmitEmptyStringPtr ([idx:106][key:parentSessionName][offset:16])
[100]---StructFieldOmitEmptyStringPtr ([idx:106][key:subSessionName][offset:24])
[101]---StructFieldOmitEmptySlice ([idx:106][key:viewGroups][offset:32])
[102]---Slice ([idx:111][elemIdx:112][length:113])
[103]----String ([idx:114])
[104]---SliceElem ([idx:111][elemIdx:112][length:113][size:16])
[105]---SliceEnd ([idx:116])
[106]---StructEnd ([idx:117][key:][offset:0])
[107]--StructFieldOmitEmptySlice ([idx:5][key:externalIds][offset:192])
[108]--Slice ([idx:118][elemIdx:119][length:120])
[109]---String ([idx:121])
[110]--SliceElem ([idx:118][elemIdx:119][length:120][size:16])
[111]--SliceEnd ([idx:123])
[112]--StructFieldOmitEmptyStringPtr ([idx:5][key:brainType][offset:216])
[113]--StructEndOmitEmptyStringPtr ([idx:5][key:clockType][offset:224])
[114]-StructFieldOmitEmptyMarshalJSONPtr ([idx:2][key:lastModified][offset:32])
[115]-StructFieldOmitEmptyIntPtr ([idx:2][key:startFrameID][offset:40])
[116]-StructFieldOmitEmptyIntPtr ([idx:2][key:endFrameID][offset:48])
[117]-StructFieldOmitEmptyIntPtr ([idx:2][key:startFrameIDExtended][offset:56])
[118]-StructFieldOmitEmptyIntPtr ([idx:2][key:endFrameIDExtended][offset:64])
[119]-StructFieldOmitEmptyIntPtr ([idx:2][key:firstGfiIndex][offset:72])
[120]-StructFieldOmitEmptyIntPtr ([idx:2][key:lastGfiIndex][offset:80])
[121]-StructFieldOmitEmptyStringPtr ([idx:2][key:dataState][offset:88])
[122]-StructFieldOmitEmpty ([idx:2][key:gpsMiddleCoordinate][offset:112])
[123]--StructPtrHeadOmitEmptyString ([idx:135][key:type][offset:0])
[124]--StructFieldOmitEmptySlicePtr ([idx:135][key:coordinates][offset:16])
[125]--Slice ([idx:137][elemIdx:138][length:139])
[126]---Float64 ([idx:140])
[127]--SliceElem ([idx:137][elemIdx:138][length:139][size:8])
[128]--SliceEnd ([idx:142])
[129]--StructEnd ([idx:143][key:][offset:0])
[130]-StructFieldOmitEmpty ([idx:2][key:bypassLogging][offset:120])
[131]--StructPtrHeadOmitEmptyBoolPtr ([idx:144][key:availability][offset:0])
[132]--StructFieldOmitEmpty ([idx:144][key:validity][offset:8])
[133]---StructPtrHeadOmitEmptyString ([idx:146][key:isValid][offset:0])
[134]---StructEndOmitEmptyString ([idx:146][key:value][offset:16])
[135]--StructEnd ([idx:148][key:][offset:0])
[136]-StructFieldOmitEmptySlice ([idx:2][key:listNames][offset:128])
[137]-Slice ([idx:149][elemIdx:150][length:151])
[138]--StringPtr ([idx:152])
[139]-SliceElem ([idx:149][elemIdx:150][length:151][size:8])
[140]-SliceEnd ([idx:154])
[141]-StructFieldOmitEmptySlice ([idx:2][key:trainTestClassifications][offset:152])
[142]-Slice ([idx:156][elemIdx:157][length:158])
[143]---StructPtrHeadOmitEmptyString ([idx:159][key:tech][offset:0])
[144]---StructFieldOmitEmptyString ([idx:159][key:user][offset:16])
[145]---StructEndOmitEmptyString ([idx:159][key:classification][offset:32])
[146]-SliceElem ([idx:156][elemIdx:157][length:158][size:8])
[147]-SliceEnd ([idx:163])
[148]-StructFieldOmitEmptySlice ([idx:2][key:metadata][offset:176])
[149]-Slice ([idx:165][elemIdx:166][length:167])
[150]---StructPtrHeadMarshalJSONPtr ([idx:168][key:id][offset:0])
[151]---StructFieldOmitEmptyStringPtr ([idx:168][key:category][offset:8])
[152]---StructFieldOmitEmptyMarshalJSONPtr ([idx:168][key:timestamp][offset:16])
[153]---StructFieldOmitEmpty ([idx:168][key:value][offset:24])
[154]---Interface ([idx:172])
[155]---StructFieldOmitEmptyBoolPtr ([idx:168][key:default][offset:40])
[156]---StructFieldOmitEmptyStringPtr ([idx:168][key:source][offset:48])
[157]---StructFieldOmitEmptyStringPtr ([idx:168][key:sourceDescription][offset:56])
[158]---StructFieldOmitEmptyStringPtr ([idx:168][key:isValid][offset:64])
[159]---StructEndOmitEmptyStringPtr ([idx:168][key:referTo][offset:72])
[160]-SliceElem ([idx:165][elemIdx:166][length:167][size:8])
[161]-SliceEnd ([idx:179])
[162]-StructFieldOmitEmptyMarshalJSONPtr ([idx:2][key:artifactsLastModified][offset:200])
[163]-StructFieldOmitEmpty ([idx:2][key:clipext][offset:208])
[164]--StructPtrHeadOmitEmptyStringPtr ([idx:182][key:jpgCompressionStatus][offset:0])
[165]--StructFieldOmitEmptyMarshalJSONPtr ([idx:182][key:lastModified][offset:8])
[166]--StructFieldOmitEmptyStringPtr ([idx:182][key:mestVersion][offset:16])
[167]--StructEndOmitEmptyStringPtr ([idx:182][key:metaStatus][offset:24])
[168]-StructFieldOmitEmpty ([idx:2][key:uiOptimization][offset:216])
[169]--StructPtrHeadOmitEmptyBoolPtr ([idx:187][key:foeExcludeInvalid][offset:0])
[170]--StructFieldOmitEmptyBoolPtr ([idx:187][key:gpsExcludeInvalid][offset:8])
[171]--StructFieldOmitEmptyBoolPtr ([idx:187][key:yawRateExcludeInvalid][offset:16])
[172]--StructFieldOmitEmptyBoolPtr ([idx:187][key:signalsExcludeInvalid][offset:24])
[173]--StructFieldOmitEmptyBoolPtr ([idx:187][key:etcExcludeInvalid][offset:32])
[174]--StructFieldOmitEmptyBoolPtr ([idx:187][key:cam2camExcludeInvalid][offset:40])
[175]--StructEndOmitEmptyBoolPtr ([idx:187][key:oneClipPerContinuousSession][offset:48])
[176]-StructFieldOmitEmpty ([idx:1][key:drops][offset:8])
[177]--StructPtrHead ([idx:195][key:Drops][offset:0])
[178]--StructPtrHeadOmitEmptyFloat64Ptr ([idx:196][key:frameDropsPercentage][offset:32])
[179]--StructFieldOmitEmptyFloat64Ptr ([idx:196][key:imageDropsPercentage][offset:40])
[180]--StructFieldOmitEmptyFloat64Ptr ([idx:196][key:brainDropsPercentage][offset:48])
[181]--StructFieldOmitEmptyFloat64Ptr ([idx:196][key:signalDropsPercentage][offset:56])
[182]--StructFieldOmitEmptySlicePtr ([idx:195][key:frameDropsRanges][offset:8])
[183]--Slice ([idx:201][elemIdx:202][length:203])
[184]----StructPtrHeadOmitEmptyInt ([idx:204][key:start][offset:0])
[185]----StructEndOmitEmptyInt ([idx:204][key:end][offset:8])
[186]--SliceElem ([idx:201][elemIdx:202][length:203][size:8])
[187]--SliceEnd ([idx:207])
[188]--StructFieldOmitEmptySlicePtr ([idx:195][key:imageDropsRanges][offset:16])
[189]--Slice ([idx:209][elemIdx:210][length:211])
[190]----StructPtrHeadOmitEmptyInt ([idx:212][key:start][offset:0])
[191]----StructEndOmitEmptyInt ([idx:212][key:end][offset:8])
[192]--SliceElem ([idx:209][elemIdx:210][length:211][size:8])
[193]--SliceEnd ([idx:215])
[194]--StructFieldOmitEmptySlicePtr ([idx:195][key:brainDropsRanges][offset:24])
[195]--Slice ([idx:217][elemIdx:218][length:219])
[196]----StructPtrHeadOmitEmptyInt ([idx:220][key:start][offset:0])
[197]----StructEndOmitEmptyInt ([idx:220][key:end][offset:8])
[198]--SliceElem ([idx:217][elemIdx:218][length:219][size:8])
[199]--SliceEnd ([idx:223])
[200]--StructFieldOmitEmptySlicePtr ([idx:195][key:signalDropsRanges][offset:32])
[201]--Slice ([idx:225][elemIdx:226][length:227])
[202]----StructPtrHeadOmitEmptyInt ([idx:228][key:start][offset:0])
[203]----StructEndOmitEmptyInt ([idx:228][key:end][offset:8])
[204]--SliceElem ([idx:225][elemIdx:226][length:227][size:8])
[205]--SliceEnd ([idx:231])
[206]--StructEnd ([idx:232][key:][offset:0])
[207]-StructFieldOmitEmpty ([idx:1][key:dataLocations][offset:16])
[208]--StructPtrHeadOmitEmptyStringPtr ([idx:233][key:onPrem][offset:0])
[209]--StructFieldBool ([idx:233][key:onAWS][offset:8])
[210]--StructFieldBool ([idx:233][key:onAWSChina][offset:9])
[211]--StructEndOmitEmptyStringPtr ([idx:233][key:compressed][offset:16])
[212]-StructFieldSlice ([idx:1][key:labels][offset:24])
[213]-Slice ([idx:238][elemIdx:239][length:240])
[214]---StructPtrHead ([idx:241][key:Metadata][offset:0])
[215]---StructPtrHeadMarshalJSONPtr ([idx:242][key:id][offset:0])
[216]---StructFieldOmitEmptyStringPtr ([idx:242][key:category][offset:8])
[217]---StructFieldOmitEmptyMarshalJSONPtr ([idx:242][key:timestamp][offset:16])
[218]---StructFieldOmitEmpty ([idx:242][key:value][offset:24])
[219]---Interface ([idx:246])
[220]---StructFieldOmitEmptyBoolPtr ([idx:242][key:default][offset:40])
[221]---StructFieldOmitEmptyStringPtr ([idx:242][key:source][offset:48])
[222]---StructFieldOmitEmptyStringPtr ([idx:242][key:sourceDescription][offset:56])
[223]---StructFieldOmitEmptyStringPtr ([idx:242][key:isValid][offset:64])
[224]---StructFieldOmitEmptyStringPtr ([idx:242][key:referTo][offset:72])
[225]---StructEnd ([idx:252][key:][offset:0])
[226]-SliceElem ([idx:238][elemIdx:239][length:240][size:8])
[227]-SliceEnd ([idx:253])
[228]-StructFieldSlice ([idx:1][key:validations][offset:48])
[229]-Slice ([idx:255][elemIdx:256][length:257])
[230]---StructPtrHead ([idx:258][key:Metadata][offset:0])
[231]---StructPtrHeadMarshalJSONPtr ([idx:259][key:id][offset:0])
[232]---StructFieldOmitEmptyStringPtr ([idx:259][key:category][offset:8])
[233]---StructFieldOmitEmptyMarshalJSONPtr ([idx:259][key:timestamp][offset:16])
[234]---StructFieldOmitEmpty ([idx:259][key:value][offset:24])
[235]---Interface ([idx:263])
[236]---StructFieldOmitEmptyBoolPtr ([idx:259][key:default][offset:40])
[237]---StructFieldOmitEmptyStringPtr ([idx:259][key:source][offset:48])
[238]---StructFieldOmitEmptyStringPtr ([idx:259][key:sourceDescription][offset:56])
[239]---StructFieldOmitEmptyStringPtr ([idx:259][key:isValid][offset:64])
[240]---StructFieldOmitEmptyStringPtr ([idx:259][key:referTo][offset:72])
[241]---StructEnd ([idx:269][key:][offset:0])
[242]-SliceElem ([idx:255][elemIdx:256][length:257][size:8])
[243]-SliceEnd ([idx:270])
[244]-StructEnd ([idx:271][key:][offset:0])

* [CONTEXT]
&{Context:<nil> Buf:[123 34 110 97 109 101 34 58 34 52 57 98 56 99 98 99 101 49 99 95 49 55 45 49 50 45 49 51 95 48 57 45 49 48 45 53 49 95 72 83 69 51 54 48 95 83 70 50 95 49 50 56 95 48 48 49 51 34 44 34 115 101 110 115 111 114 115 46 115 110 34 44 34 109 105 115 115 105 110 103 34 58 34 78 47 65 34 44 34 115 105 122 101 34 58 49 48 48 48 48 125 125 125 44 34 110 101 115 116 101 100 34 58 123 34 112 97 116 104 34 58 34 115 101 110 115 111 114 115 34 125 125 125 44] MarshalBuf:[] Ptrs:[274885816768 274963172160 274955054592 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] KeepRefs:[0x400078b1c0] SeenPtr:[] BaseIndent:0 Prefix:[] IndentStr:[] Option:0x4003c2a700}
===================================
[2023-05-25 12:34:55.528] ~ERROR~ [722f9a72e614af25] [Error: runtime error: invalid memory address or nil pointer dereference] PANIC: 
goroutine 73 [running]:
runtime/debug.Stack()
panic({0x13c9780, 0x2b5e980})
	/usr/local/go/src/runtime/panic.go:890 +0x21c
github.com/goccy/go-json/internal/encoder/vm.DebugRun.func1()
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/vm/debug_vm.go:36 +0x4c0
panic({0x13c9780, 0x2b5e980})
	/usr/local/go/src/runtime/panic.go:890 +0x21c
github.com/goccy/go-json/internal/encoder/vm.Run(0x40007b4680, {0x400015f000, 0x3b, 0x400}, 0x400514d500)
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/vm/vm.go:26 +0xc4
github.com/goccy/go-json/internal/encoder/vm.DebugRun(0x40007b4680, {0x400015f000, 0x0, 0x400}, 0x400514d500)
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/internal/encoder/vm/debug_vm.go:40 +0xb4
github.com/goccy/go-json.encodeRunCode(0x40007b4680, {0x400015f000, 0x0, 0x400}, 0x400514d500)
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:305 +0x13c
github.com/goccy/go-json.encode(0x40007b4680, {0x13d46c0, 0x400078b1c0})
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:235 +0x214
github.com/goccy/go-json.(*Encoder).encodeWithOption(0x4005137e80, 0x40007b4680, {0x13d46c0, 0x400078b1c0}, {0x400510e6c0, 0x1, 0x1})
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:77 +0x26c
github.com/goccy/go-json.(*Encoder).EncodeWithOption(0x4005137e80, {0x13d46c0, 0x400078b1c0}, {0x400510e6c0, 0x1, 0x1})
	/workspace/go/pkg/mod/github.com/goccy/go-json@v0.10.2/encode.go:42 +0x6c

```

**Comment by nikolaydimitrov** [comment]
How does that object look like?
