### ISSUE TITLE
enconter panic when calling unmarshal()

### ISSUE THREAD

**Issue by PearsonCHN** [goccy/go-json#495]
```

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xa0cc93]
--
goroutine 698 [running]:
github.com/goccy/go-json/internal/decoder.(*structDecoder).Decode(0x0, 0xc0019a8100, 0x1e0?, 0xc000faa000?, 0xc000fca000) 	/builds/worker/vendor/github.com/goccy/go-json/internal/decoder/struct.go:760 +0x3f3
github.com/goccy/go-json.unmarshal({0xc000faa000?, 0xc0016ad428?, 0xb287a6?}, {0x1e42420, 0xc000fca000}, {0x0, 0x0, 0x59?}) 	/builds/worker/vendor/github.com/goccy/go-json/decode.go:47 +0x186
github.com/goccy/go-json.Unmarshal(...) 	/builds/worker/vendor/github.com/goccy/go-json/json.go:276

```

go-json version in go.mod is v0.9.10

**Comment by 3AceShowHand** [comment]
Do you have reproduce scripts? I think I also meet this problem, but don't know how to reproduce since lack of data

**Comment by Yu-HuanWu** [comment]
Looks like an issue i've encountered as well. The problem seems to be that the `structDecoder`, `d`, in the `Decode` func is `nil`.

I have a PR for this bandaid fix: https://github.com/goccy/go-json/pull/557

The actual root cause is most likely due to race condition, where the shared `cachedDecoder` map was being written to and read from by multiple goroutines without any synchronization.

To reproduce this panic, I wrote this test utilizing `t.Parallel`:

```go
import (
	"sync"
	"testing"

	gojson "github.com/goccy/go-json"
)

// simple, valid struct that should never fail.
type ValidStruct struct {
	SID string `json:"sid"`
}

// this struct contains a function field, which is an unsupported type that should trigger the silent (nil, nil) return from the decoder's compiler.
type WillFailStruct struct {
	ID   int
	Func func()
}

func TestGojsonUnmarshal(t *testing.T) {
	t.Run("Will Fail", func(t *testing.T) {
		t.Parallel() 

		willFailJSON := []byte(`{"ID": 1}`)
		var f WillFailStruct
		for i := 0; i < 1000; i++ {
			_ = gojson.Unmarshal(willFailJSON, &f)
		}
	})

	t.Run("Valid Struct", func(t *testing.T) {
		t.Parallel() 

		validJSON := []byte(`{"sid":"12345"}`)
		var v ValidStruct

		var wg sync.WaitGroup
		numGoroutines := 100
		wg.Add(numGoroutines)

		for i := 0; i < numGoroutines; i++ {
			go func() {
				defer wg.Done()
				for j := 0; j < 100; j++ {
					func() {
						defer func() {
							if r := recover(); r != nil {
								t.Errorf("PANIC DETECTED while unmarshaling a valid struct. This proves the cache was polluted. Panic: %v", r)
							}
						}()
						_ = gojson.Unmarshal(validJSON, &v)
					}()
				}
			}()
		}
		wg.Wait()
	})
}
```

When i ran `go test -race -v`, I was able to see `WARNING: DATA RACE`

Hope this helps.

**Comment by TelpeNight** [comment]
Similar bug: https://github.com/goccy/go-json/issues/566
Potential fix: https://github.com/goccy/go-json/pull/567

**Comment by Uzer007-admin** [comment]
Please accept this PR. There are errors in the final product.
Potential fix: https://github.com/goccy/go-json/pull/567

**Comment by Spikhalskiy** [comment]
Just hit this on v0.10.5, and it happens on our code without the 'unsupported type' condition used in @Yu-HuanWu repro, which points at [#582](https://github.com/chalk-ai/chalk-private/issues/582) (not #557) as the real fix for the original bug.

goccy/go-json: v0.10.5 go: 1.26.2 GOOS/GOARCH: linux/amd64 (Debian 12)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a510da]
goroutine 63 [running]:
testing.tRunner.func1.2({0x3e072a0, 0x83fc570})
	/go-cache/go-1.26.2/src/testing/testing.go:1974 +0x232
testing.tRunner.func1()
	/go-cache/go-1.26.2/src/testing/testing.go:1977 +0x349
panic({0x3e072a0?, 0x83fc570?})
	/go-cache/go-1.26.2/src/runtime/panic.go:860 +0x13a
github.com/goccy/go-json/internal/decoder.(*sliceDecoder).Decode(0x844d1c0?, 0x350c35761e00?, 0x350c35761e00?, 0x350c36086518?, 0x350c35761e00)
	/go-cache/mod/github.com/goccy/go-json@v0.10.5/internal/decoder/slice.go:234 +0x2fa
github.com/goccy/go-json.unmarshal({0x350c36086518?, 0x0?, 0x0?}, {0x3af95e0, 0x350c35761e00}, {0x0, 0x0, 0x350c34648008?})
	/go-cache/mod/github.com/goccy/go-json@v0.10.5/decode.go:47 +0x167
github.com/goccy/go-json.Unmarshal(...)
	/go-cache/mod/github.com/goccy/go-json@v0.10.5/json.go:274
```

Hit inside a Go test binary run with `go test -parallel 32 -shuffle=on ./...`, i.e. many tests across many packages calling Unmarshal on distinct types for the first time concurrently right as the process starts up - same 'cold cache, high concurrency' shape as discussed here.

The type being decoded is `[]T`, where `T` is:

```
type T struct {
	StorageRole   int32   `json:"storage_role"`
	EnvironmentId *MyID   `json:"environment_id"` // MyID is `type MyID string`, no custom (Un)MarshalJSON
	ClusterId     *string `json:"cluster_id"`
	Uri           string  `json:"uri"`
}
```

**Comment by pekashy** [comment]
Also reproducing for me on 10.5

```go
package json_test

import (
	"strings"
	"sync"
	"testing"

	"github.com/goccy/go-json"
)

func TestDecoderCacheRace(t *testing.T) {
	const doc = `{"a":1,"b":"x"}`
	var wg sync.WaitGroup
	for i := 0; i < 64; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := 0; j < 100; j++ {
				var v map[string]any
				d := json.NewDecoder(strings.NewReader(doc))
				d.UseNumber()
				_ = d.Decode(&v)
			}
		}()
	}
	wg.Wait()
}
```

**Comment by TelpeNight** [comment]
Quick fix until new release:

```
replace github.com/goccy/go-json => github.com/TelpeNight/goccy-go-json v0.10.7
```
