### ISSUE TITLE
【Bug】Error encountered during Benckmark testing

### ISSUE THREAD

**Issue by Fgaoxing** [goccy/go-json#515]
## code
```golang
package main_test

import (
	"testing"

	"github.com/goccy/go-json"
)

func BenchmarkMain(b *testing.B) {
	for i := 0; i < b.N; i++ {
		jsonObj := struct {
			Test1 string `json:"test1"`
			Test2 string `json:"test2"`
			Test3 string `json:"test3"`
			Test4 string `json:"test4"`
		}{
			Test1: "test1",
			Test2: "test2",
			Test3: "test3",
			Test4: "test4",
		}
		data := []byte{}
		json.Unmarshal(data, &jsonObj)
	}
}
```
## Log
```shell
D:\**\jsontest>go test -benchmem . -bench=^Benchmark -cpuprofile ./cpu.pprof
panic: runtime error: slice bounds out of range [1:0]

goroutine 36 [running]:
reflect.StructTag.Lookup({0x9f478a, 0xc}, {0xa3055e?, 0x4})
        C:/Program Files/Go/src/reflect/type.go:937 +0x298
reflect.StructTag.Get(...)
        C:/Program Files/Go/src/reflect/type.go:914
github.com/goccy/go-json/internal/runtime.getTag(...)
        C:/Users/Yoga/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/runtime/struct_field.go:10
github.com/goccy/go-json/internal/runtime.IsIgnoredStructField({{0x9f4784, 0x5}, {0x0, 0x0}, {0xa80af0, 0x9fdb60}, {0x9f478a, 0xc}, 0x0, {0xc000100098, ...}, ...})
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/runtime/struct_field.go:28 +0xee
github.com/goccy/go-json/internal/decoder.typeToStructTags(0xa19920)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/decoder/compile.go:318 +0x145
github.com/goccy/go-json/internal/decoder.compileStruct(0xa19920, {0x0, 0x0}, {0x0, 0x0}, 0xc00012de38)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/decoder/compile.go:336 +0x247
github.com/goccy/go-json/internal/decoder.compile(0xa19920, {0x0, 0x0}, {0x0, 0x0}, 0xc0002a3e38)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/decoder/compile.go:82 +0x8f1
github.com/goccy/go-json/internal/decoder.compileHead(0x9fbde0, 0xc0002a3e38)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/decoder/compile.go:67 +0x130
github.com/goccy/go-json/internal/decoder.CompileToGetDecoder(0x9fbde0?)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/internal/decoder/compile_norace.go:23 +0xe9
github.com/goccy/go-json.unmarshal({0xc0002a3f38?, 0x668c01fb?, 0x70000c00609ce90?}, {0x9fbde0, 0xc00009a000}, {0x0, 0x0, 0x934b72?})
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/decode.go:37 +0x8b
github.com/goccy/go-json.Unmarshal(...)
        C:/Users/**/go/pkg/mod/github.com/goccy/go-json@v0.10.3/json.go:274
jsontest_test.BenchmarkMain(0xc00005e288)
        D:/Desktop/OAC/jsontest/main_test.go:23 +0x87
testing.(*B).runN(0xc00005e288, 0x1)
        C:/Program Files/Go/src/testing/benchmark.go:193 +0xf8
testing.(*B).run1.func1()
        C:/Program Files/Go/src/testing/benchmark.go:215 +0x4e
created by testing.(*B).run1 in goroutine 1
        C:/Program Files/Go/src/testing/benchmark.go:208 +0x90
exit status 2
FAIL    jsontest        0.322s
FAIL
```

On Windows10 and go version 1.22.5

**Comment by Fgaoxing** [comment]
@
