### ISSUE TITLE
Panic with invalid data

### ISSUE THREAD

**Issue by johejo** [goccy/go-json#98]
Found in go-fuzz
https://github.com/dvyukov/go-fuzz

Test code

```go
package json_test

import (
	"testing"

	"github.com/goccy/go-json"
)

func TestPanic(t *testing.T) {
	data := "[\"\\"
	var i interface{}
	json.Unmarshal([]byte(data), &i)
}
```

Output

```
=== RUN   TestPanic
--- FAIL: TestPanic (0.00s)
panic: runtime error: index out of range [4] with length 4 [recovered]
        panic: runtime error: index out of range [4] with length 4

goroutine 19 [running]:
testing.tRunner.func1.1(0xa087c0, 0xc0001542c0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.7/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000102900)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.7/libexec/src/testing/testing.go:1075 +0x41a
panic(0xa087c0, 0xc0001542c0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.7/libexec/src/runtime/panic.go:969 +0x1b9
github.com/goccy/go-json.(*interfaceDecoder).decode(0xc00011da70, 0xc0001244f0, 0x4, 0x4, 0x1, 0xc000138d00, 0x7f5b2a9bdaa8, 0xdc2b80, 0x0)
        /home/heijo/ghq/github.com/goccy/go-json/decode_interface.go:218 +0x1431
github.com/goccy/go-json.(*sliceDecoder).decode(0xc00017f340, 0xc0001244f0, 0x4, 0x4, 0x0, 0xc000187d78, 0x0, 0x0, 0xc00017f340)
        /home/heijo/ghq/github.com/goccy/go-json/decode_slice.go:197 +0x518
github.com/goccy/go-json.(*interfaceDecoder).decode(0xc00011da10, 0xc0001244f0, 0x4, 0x4, 0x0, 0xc0001194f0, 0x10, 0xdc2b80, 0x0)
        /home/heijo/ghq/github.com/goccy/go-json/decode_interface.go:204 +0x574
github.com/goccy/go-json.(*Decoder).decode(0xc00005c758, 0xc0001244f0, 0x4, 0x4, 0xc00006ef08, 0xc0001244f0, 0xc0001244f0)
        /home/heijo/ghq/github.com/goccy/go-json/decode.go:103 +0x106
github.com/goccy/go-json.(*Decoder).decodeForUnmarshal(0xc00005c758, 0xc0001244f0, 0x4, 0x4, 0x96cda0, 0xc0001194f0, 0xc00005c748, 0x46da5b)
        /home/heijo/ghq/github.com/goccy/go-json/decode.go:112 +0x65
github.com/goccy/go-json.Unmarshal(...)
        /home/heijo/ghq/github.com/goccy/go-json/json.go:301
github.com/goccy/go-json_test.TestPanic(0xc000102900)
        /home/heijo/ghq/github.com/goccy/go-json/bugs_test.go:12 +0xeb
testing.tRunner(0xc000102900, 0xa75ea8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.7/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.7/libexec/src/testing/testing.go:1168 +0x2b3
FAIL    github.com/goccy/go-json        0.006s
FAIL
```

**Comment by lestrrat** [comment]
This fixes the issue

```diff
diff --git a/decode_interface.go b/decode_interface.go
index 2138f68..ac74036 100644
--- a/decode_interface.go
+++ b/decode_interface.go
@@ -214,7 +214,12 @@ func (d *interfaceDecoder) decode(buf []byte, cursor int64, p unsafe.Pointer) (i
        case '"':
                cursor++
                start := cursor
+               l := int64(len(buf))
                for {
+                       if l <= cursor + 1 {
+                               return 0, errUnexpectedEndOfJSON("string", cursor)
+                       }
+
                        switch buf[cursor] {
                        case '\\':
                                cursor++
diff --git a/json_test.go b/json_test.go
index a73db50..48dc8aa 100644
--- a/json_test.go
+++ b/json_test.go
@@ -299,3 +299,9 @@ func genMap(n int) map[string]interface{} {
        }
        return x
 }
+
+func TestGHIssue98(t *testing.T) {
+       data := "[\"\\"
+       var i interface{}
+       json.Unmarshal([]byte(data), &i)
+}
```
